version: "3"

services:
  server:
    build: servidor/
    command: python3 servidor.py
    ports:
      - "5000:5000"
    volumes:
      - ./servidor:/servidor/

  client:
    build: cliente/
    command: python3 cliente.py
    volumes:
      - ./cliente:/cliente/
    depends_on:
      - server
