version: "3"

services:
  headnode:
    container_name: Headnode
    stdin_open: true
    tty: true
    build: headnode/
    command: python ./Headnode.py
    ports:
      - "5000:5000"
    network_mode: host
    volumes:
      - ./headnode:/headnode
  cliente:
    container_name: Cliente
    stdin_open: true
    tty: true
    build: cliente/
    command: python ./Dummy.py
    network_mode: host
    volumes:
      - ./cliente:/cliente
    depends_on:
      - headnode
      - datanode
  datanode:
    build: datanode/
    command: python ./Datanode.py
    network_mode: host
    volumes:
      - ./datanode:/datanode
    depends_on:
      - headnode